/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}","./components/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary":                  "#002452",
        "on-primary":               "#ffffff",
        "primary-container":        "#1b3a6b",
        "on-primary-container":     "#89a5dd",
        "secondary":                "#00696d",
        "on-secondary":             "#ffffff",
        "secondary-container":      "#9df0f4",
        "on-secondary-container":   "#037074",
        "error":                    "#ba1a1a",
        "on-error":                 "#ffffff",
        "error-container":          "#ffdad6",
        "on-error-container":       "#93000a",
        "background":               "#f9f9ff",
        "on-background":            "#131c2a",
        "surface":                  "#f9f9ff",
        "on-surface":               "#131c2a",
        "on-surface-variant":       "#44474f",
        "surface-variant":          "#dae3f7",
        "surface-container-lowest": "#ffffff",
        "surface-container-low":    "#f0f3ff",
        "surface-container":        "#e7eeff",
        "surface-container-high":   "#dfe8fd",
        "surface-container-highest":"#dae3f7",
        "surface-tint":             "#425e91",
        "outline":                  "#747780",
        "outline-variant":          "#c4c6d0",
        "accent":                   "#F5A623",
        "accent-light":             "#FFF3D6",
      },
      fontFamily: {
        sans:          ["'Plus Jakarta Sans'","sans-serif"],
        mono:          ["'JetBrains Mono'","monospace"],
        "headline-md": ["'Plus Jakarta Sans'"],
        "body-md":     ["'Plus Jakarta Sans'"],
        "body-sm":     ["'Plus Jakarta Sans'"],
        "label-caps":  ["'Plus Jakarta Sans'"],
        "data-mono":   ["'JetBrains Mono'"],
        "data-lg-mono":["'JetBrains Mono'"],
      },
      fontSize: {
        "headline-md": ["24px",{lineHeight:"32px",fontWeight:"600"}],
        "body-md":     ["16px",{lineHeight:"24px",fontWeight:"400"}],
        "body-sm":     ["14px",{lineHeight:"20px",fontWeight:"400"}],
        "label-caps":  ["12px",{lineHeight:"16px",letterSpacing:"0.05em",fontWeight:"700"}],
        "data-mono":   ["14px",{lineHeight:"20px",letterSpacing:"0.02em",fontWeight:"500"}],
        "data-lg-mono":["18px",{lineHeight:"24px",fontWeight:"600"}],
      },
      borderRadius: {
        DEFAULT:"0.25rem",lg:"0.5rem",xl:"0.75rem",
        "2xl":"1rem","3xl":"1.5rem",full:"9999px",
      },
      spacing: {
        "sidebar-width": "280px",
        "topbar-height": "72px",
        "gutter":        "24px",
        "margin-mobile": "16px",
        "margin-desktop":"32px",
      },
      boxShadow: {
        glass:    "0 4px 24px rgba(27,58,107,0.08)",
        "glass-lg":"0 8px 40px rgba(27,58,107,0.12)",
        topbar:   "0 2px 8px rgba(27,58,107,0.06)",
      },
    },
  },
  plugins: [],
};
